### ISSUE TITLE
ROOT TEXT conversion

### ISSUE THREAD

**Issue by junholeephy** [StudyGroupPKU/fruit_team#3]
재근아, 일단 정말 수고 많았어 ㅎㅎㅎ  짧은 시간 안에 이렇게 하기 쉽지 않았을텐데 대단하구만!! ㅎㅎㅎ

먼저 우리가 이 코드 작성하는 취지를 생각해봤을때,  txt -> ROOT -> txt -> ROOT ->txt .... 이런식으로 무한 반복 재생산이 가능해야 해.
근데 "mcode_txt_to_ROOT.py" 코드 에선 첫째  bin의 entry가 0이고, entry number에 대응하는 bin이 하나씩 뒤로 밀려서 나오는것같아. 한번 확인해보고, 디버깅 필요하면, 해서 다시 올려줘 ㅎㅎ

**Comment by junholeephy** [comment]
그리고 일단은 내가 ROOT랑 txt 파일 전환하는 코드를 함수화 시켜서 만들었어, 아래 링크 보면 있어. 
https://github.com/StudyGroupPKU/fruit_team/tree/master/Project/functions
전환시키고 싶은 파일 넣으면 전환 되서 나오는거 확인 할수 있을꺼야. 
(한가지 주의 할점은, 내  input txt 파일은 4줄로 작성했어(bin_num, bin_init, bin_final, Entry). 코드 실행시켜 보면 알수 있을듯!)

현재 우리가 완성한 작업은 아래와 같아 : 
(1) 지정된 bin, Entry가 적힌 txt파일을 input하면, 대응하는 histogram ".root" 파일을 얻을수 있다.
(2) histogram ".root"를  input하면, 지정된 형식의 txt파일을 얻을수 있다.
(3) txt 파일과 dat 파일 간에는, 본질 적인 구분이 없기 때문에, ".dat"형식도 읽고 쓰기 가능할것 같다( 시험 해봐야함)
(4) output파일의 path를 설정할수 있다.

우리가 앞으로 했으면 하는 작업은 아래와 같아:
(1) 어떤 형식의 데이터가 와도, 우리가 규정해 놓은 txt 파일 형식에 맞게 output하게하는 python 코드 구현.
(2) TTree, TBranch 활용한 다원 데이터 전환 프레임.
(3) 다차원 데이터 전환 프레임. (TH2)

**Comment by manggny** [comment]
옙 !! ㅎㅎ 제가 목요일 오후에 또 발표가 하나 잇어서요 ㅠㅠ 그것만 끝나면 다시한번 돌려볼게요 ! ㅎㅎ

**Comment by manggny** [comment]
음 아니면 루트 파일을 텍스트로 변환할때 첫 열을 bin 으로 하지 말고 실제 대응하는 x 값으로 하는것도 좋을거 같아요 ! bin값으로 하니 원 그래프에서 x축 범위를 알 수 없어서 함수로 보편화 하기 쉽지 않네요.

**Comment by junholeephy** [comment]
웅웅,내 txt파일 보면, 4줄이 있는데. 차례로 bin, 해당bin 실제대응하는 x 시작값, 해당bin 실제대응하는 x끝값, entry 이렇게 저장되 있어 
https://github.com/StudyGroupPKU/fruit_team/blob/master/Project/functions/_processed.txt
